theme: minima
#remote_theme: jekyll/minima

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Site settings
#    Used to personalize the site. If you look in the HTML files,
#    you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#    You can create any custom variable you like, and they will be accessible
#    in the templates via {{ site.myvariable }} for example.
url: "https://locha-usd.github.io" 
baseurl: "" # the subpath of your site if neded, e.g. /sitecontent

title: locha-usd.github.io
description: >- # this means to ignore newlines
  Feasibility study for custom digital assets implementation by developing countries with Liquid Network


github_link: https://github.com/locha-usd/locha-usd.github.io
twitter_link: https://twitter.com/cointigo

include: [".well-known", ".nojekyll"]
